---
- name: rm previous raft snapshot
  file:
    path: "/home/centos/raft.snap"
    state: absent

- name: take a raft snapshot
  shell: "bash -c \"{{ vault_bin_path }}/vault operator raft snapshot save raft.snap\""
  