---
- name: Include OS specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - vars

- name: Ensure required OS packages are installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ vault_os_packages }}"