---
# handlers file for ansible-lss-vault-upgrade
- name: start vault
  systemd:
    name: vault
    state: started

- name: stop vault
  systemd:
    name: vault
    state: stopped

- name: restart vault
  systemd:
    name: vault
    state: restarted